### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by marcverhagen**
Finally merging in all the NER-related changes on the develop branch. The only possibly contentious issue is the change made to the directory structure, which is up for discussion.

### CODE REVIEW

**Comment by marcverhagen** [comment]
Okay, I can split it into a few smaller PRs. I think not merging some because they are not quite ready (lack of guidelines for example) may not be an option since it would hold everything up, and incompleteness has never stopped us before. I don't get remark 3 (a branch's name is what it is), but agree with 4.

**Comment by marcverhagen** [comment]
Rebasing this into neat little topical branches does not seem to be as easy as I thought because there are no clear commits that do either one of another thing, rather, some do a couple of things at the same time, which was not great design of course (there is one exception, the first commit on develop after the last merge into main is neat). So I do not know how to separate commits that change the directory structure from those that don't, so unless somebody else figures that out we are stuck with one PR.

I think what we need to do is start a new branch from the develop branch, called something like `directory-structure`, and merge in the main branch. Then we can undo changes to the directory structure we do not like and keep the ones we do like (note that the main branch itself is not sticking to the structure we agreed on a year ago). If this means going back to the old structure, fine, we can do that and fix the wrongs on that later. We make sure all the scripts run and that we understand the repercussions, then merge into main.

Finally, I don't see the point made in 

> I don't think a branch name develop means a lot in this repo anyway

Its meaning is vaguer perhaps because we bypass it for some commits. There is still use for a develop branch unless we really want to just dump any topic branch straight into the main branch, which almost never is a good idea. We have code updates and annotation uploads. We discussed a while ago how these have separate statuses, but did not have a clear solution that I remember, except that we thought it would be good to somehow separate them. At the moment new annotations are added on the main branch or in a separate branch.

I can see a flow where all annotations are uploaded on an annotations branch, and then from there somehow merged in with other branches (something else to discuss probably).

**Comment by keighrim** [comment]
I amended commits here and rebased them into #11 #12 #13 #14 #15 #16 . Closing this PR as outdated.

**Comment by keighrim** [comment]
We can discuss further whether we want to make `develop` branch as a staging area. But the current `develop` branch has a radically diverted history from the main, so I'm purging it for now to avoid any future confusion.

**Pull request closed without merging**
